// Import the necessary function from the Redux toolkit library.
const { createSlice } = require("@reduxjs/toolkit");

// Create a slice of your Redux state and associated reducers.
const counterSlice = createSlice({
  // Name of the slice, used for generating action types.
  name: "counter",

  // Initial state for this slice of the Redux store.
  initialState: {
    value: 0, // Initialize the counter value to 0.
  },

  // Define reducers, which are functions that modify the state.
  reducers: {
    // Reducer for incrementing the counter value.
    incremented: (state) => {
      state.value += 1; // Increase the value by 1.
    },
    // Reducer for decrementing the counter value.
    decremented: (state) => {
      state.value -= 1; // Decrease the value by 1.
    },
  },
});

// Export the action creators generated by createSlice.
export const { incremented, decremented } = counterSlice.actions;

// Export the reducer function generated by createSlice.
export default counterSlice.reducer;
